
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduleplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduleplans/finalizers
  verbs:
  - update
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduleplans/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduletriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduletriggers/finalizers
  verbs:
  - update
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduletriggers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
