# permissions for end users to view scheduleplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduleplan-viewer-role
rules:
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduleplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduleplans/status
  verbs:
  - get
