# permissions for end users to edit scheduletriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduletrigger-editor-role
rules:
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduletriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - planner.ciena.io
  resources:
  - scheduletriggers/status
  verbs:
  - get
