---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weighted-app-1
  labels:
    app: weighted-app-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weighted-app-1
  template:
    metadata:
      name: weighted-app-1
      labels:
        app: weighted-app-1
        planner.ciena.io/pod-set: planner-podset
    spec:
      schedulerName: podset-planner-scheduler
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - weighted-app-2
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: weighted-app-1
          image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weighted-app-2
  labels:
    app: weighted-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weighted-app-2
  template:
    metadata:
      name: weighted-app-2
      labels:
        app: weighted-app-2
        planner.ciena.io/pod-set: planner-podset
    spec:
      schedulerName: podset-planner-scheduler
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - weighted-app-1
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: weighted-app-2
          image: nginx
